spring:
  mandatory-file-encoding: UTF-8
  messages:
    basename: locale/messages
    cache-duration: -1
    encoding: UTF-8
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:file:C:/temp/imoveis
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: false
  sql:
    init:
      mode: always
